# Generated by Django 4.2.6 on 2023-10-18 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_verified_customuser_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
