# Generated by Django 4.1.6 on 2023-10-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_anxietytest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnxietyTest",
        ),
    ]
